services:
  n8n:
    image: n8nio/n8n:2.3.0
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Warsaw
      - N8N_HOST=10.0.1.111
      - WEBHOOK_URL=https://ending-persistent-testament-down.trycloudflare.com  # cloudflared tunnel --url http://localhost:5678
    volumes:
      - /opt/n8n_data:/home/node/.n8n